// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqUI_kmgEg3Fz9bIy8JzW_pTHMb6msLC0',
    appId: '1:394525986023:android:9ca287e18fded42883a642',
    messagingSenderId: '394525986023',
    projectId: 'ott-platform-d0c5d',
    storageBucket: 'ott-platform-d0c5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXFufBE39a2KZ-EUKy7lW-7Ng8t2J9Oqk',
    appId: '1:394525986023:ios:7ab8c3d34d9b29d783a642',
    messagingSenderId: '394525986023',
    projectId: 'ott-platform-d0c5d',
    storageBucket: 'ott-platform-d0c5d.appspot.com',
    iosBundleId: 'com.example.flutterPractise1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfjRNzFpVPx5dNw2llU5egGn1kr7kPYgI',
    appId: '1:394525986023:web:9879ead604b4914183a642',
    messagingSenderId: '394525986023',
    projectId: 'ott-platform-d0c5d',
    authDomain: 'ott-platform-d0c5d.firebaseapp.com',
    storageBucket: 'ott-platform-d0c5d.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXFufBE39a2KZ-EUKy7lW-7Ng8t2J9Oqk',
    appId: '1:394525986023:ios:7ab8c3d34d9b29d783a642',
    messagingSenderId: '394525986023',
    projectId: 'ott-platform-d0c5d',
    storageBucket: 'ott-platform-d0c5d.appspot.com',
    iosBundleId: 'com.example.flutterPractise1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfjRNzFpVPx5dNw2llU5egGn1kr7kPYgI',
    appId: '1:394525986023:web:7880690c7bd930bf83a642',
    messagingSenderId: '394525986023',
    projectId: 'ott-platform-d0c5d',
    authDomain: 'ott-platform-d0c5d.firebaseapp.com',
    storageBucket: 'ott-platform-d0c5d.appspot.com',
  );

}